version: "3.8"
services:
  proxy:
    image: nginx
    depends_on:
      - health
      - registry
      - services-registry
      - sp-registry
    volumes:
      - ./proxy:/etc/nginx/templates
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      BASE_DOMAIN: "${BASE_DOMAIN}"
    networks:
      - proxy

  health:
    container_name: health-service
    image: ghcr.io/slntopp/nocloud/health:latest
    environment:
      LOG_LEVEL: -1
      SIGNING_KEY: "${SIGNING_KEY}"
    networks:
      - proxy
      - grpc-internal
  apiserver-web:
    container_name: apiserver-web
    image: ghcr.io/slntopp/nocloud/apiserver-web:latest
    environment:
      APISERVER_HOST: proxy:8080
    networks:
      - proxy
      - grpc-internal
  registry:
    container_name: registry
    image: ghcr.io/slntopp/nocloud/registry:latest
    environment:
      LOG_LEVEL: -1
      DB_HOST: db:8529
      DB_CRED: "${DB_USER}:${DB_PASS}"
      NOCLOUD_ROOT_PASSWORD: "${NOCLOUD_ROOT_PASS}"
      SIGNING_KEY: "${SIGNING_KEY}"
    depends_on:
      - db
    networks:
      - proxy
      - arangodb
      - grpc-internal
    links:
      - db
  services-registry:
    container_name: services-registry
    image: ghcr.io/slntopp/nocloud/services-registry:latest
    environment:
      LOG_LEVEL: -1
      SIGNING_KEY: "${SIGNING_KEY}"
      DB_HOST: db:8529
      DB_CRED: "${DB_USER}:${DB_PASS}"
      DRIVERS: driver-ione:8080
    depends_on:
      - db
    networks:
      - proxy
      - arangodb
      - grpc-internal
    links:
      - db
  sp-registry:
    container_name: sp-registry
    image: ghcr.io/slntopp/nocloud/sp-registry:latest
    environment:
      LOG_LEVEL: -1
      SIGNING_KEY: "${SIGNING_KEY}"
      DB_HOST: db:8529
      DB_CRED: "${DB_USER}:${DB_PASS}"
      DRIVERS: driver-ione:8080
    networks:
      - proxy
      - arangodb
      - grpc-internal
    links:
      - db

  settings:
    image: ghcr.io/slntopp/nocloud/settings:latest
    networks:
      - grpc-internal
      - redis
    environment:
      LOG_LEVEL: -1
      REDIS_HOST: redis:6379
  redis:
    image: redis
    restart: always
    command: redis-server --save 60 1
    networks:
      - redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  db:
    container_name: database-master
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - 8529:8529
    volumes:
      - data:/var/lib/arangodb3
      - ./database/schemes/:/docker-entrypoint-initdb.d/dumps/nocloud/
    networks:
      - proxy
      - arangodb

  driver-ione:
    container_name: driver
    image: ghcr.io/slntopp/nocloud-driver-ione:latest
    networks:
      - grpc-internal

networks:
  proxy:
    driver: bridge
  grpc-internal:
  arangodb:
    driver: bridge

volumes:
  data:
