name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set target tags
        id: set-tags-matrix
        run: echo "::set-output name=matrix::$(ls Dockerfiles | jq -cnR '[inputs | select(length>0)]')"
      
    outputs:
      matrix: ${{steps.set-tags-matrix.outputs.matrix}}

  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix: 
        tag: ${{fromJson(needs.prepare.outputs.matrix)}}  

    steps:
      - name: Check
        run: echo ${{matrix}}
