name: ci

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set target tags
        id: set-tags-matrix
        run: echo "::set-output name=matrix::$(ls Dockerfiles | jq -cnR '[inputs | select(length>0)]')"
      
    outputs:
      matrix: ${{steps.set-tags-matrix.outputs.matrix}}

  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix: 
        tag: ${{fromJson(needs.prepare.outputs.matrix)}}  

    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.1
        with:
          images: ${{ env.REGISTRY }}/slntopp/nocloud/${{matrix.tag}}

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: Dockerfiles/${{matrix.tag}}/Dockerfile
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}
